spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    url: jdbc:mariadb://localhost:3306/ElevenStreet?serverTimezone=Asia/Seoul
    password: cos1234
  jpa:
    hibernate:
      format_sql: 'true'
      ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'
  devtools:
    restart:
      enabled: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'








# all good all fine


